#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# agregar esto
yarn run commit-lint $1
echo el commit debe de cumplir con estas reglas: https://nitayneeman.com/posts/understanding-semantic-commit-messages-using-git-and-angular/